import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'MAGFLOW',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        <div className="flex">
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
