import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import LoginPage from './login/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'MAGFLOW',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        <LoginPage />
      </body>
    </html>
  );
}